### ISSUE TITLE
Optimize Button Animation for Improved User Experience

### ISSUE THREAD

**Issue by Nishitbaria** [OSCode-Community/OSCodeCommunitySite#1313]
**Description:**
The current button animation on the submit button element can be improved to provide a smoother and more visually appealing user experience. The existing CSS code for the button animation has some issues, and we need to optimize it. This issue aims to update the button animation styles for better user interaction.

**Before Code:**
```css
button.submit-button[type="submit"] {
  /* background-color: #7b2fff; */
  background: linear-gradient(to right, #141e30, #243b55);
  color: #fff;
  border: none;
  letter-spacing: 1px;
  font-weight: 500;
  font-size: 20px;
  line-height: 30px;
  border-radius: 45px;
  padding: 12px 45px;
  margin: 10px 0;
  transition: all 0.3s ease;
  font-weight: 400;
  color: white;
}

button.submit-button[type="submit"]:hover {
  background: white;
  box-shadow: 0px 0 20px 5px #5081b9;
  color: black;
  font-weight: 400;
  font-family: cursive;
  transform: translateY(-2px);
}
```

**After Code:**
```css
button.submit-button[type="submit"] {
  /* background-color: #7b2fff; */
  background: linear-gradient(to right, #141e30, #243b55);
  color: #fff;
  border: none;
  letter-spacing: 1px;
  font-weight: 500;
  font-size: 20px;
  line-height: 30px;
  border-radius: 45px;
  padding: 12px 45px;
  margin: 10px 0;
  transition: all 0.3s ease;
  font-weight: 400;
  color: white;
}

button.submit-button[type="submit"]:hover {
  transition: all 1.5s ease; /* Updated: Extend the transition duration for smoother animation */
  background: white;
  box-shadow: 0px 0 20px 5px #5081b9;
  color: black;
  font-weight: 400;
  font-family: cursive;
  transform: translate(0.8); /* Updated: Use translate instead of translateY for better effect */
}

button.submit-button:focus {
  transform: translate(0.8); /* Updated: Add focus state transformation for consistency */
}
```

**Proposed Changes:**
1. **Hover Animation Duration:** The transition duration for the hover animation should be increased from `0.3s` to `1.5s` for a smoother and more gradual transition.

2. **Hover Animation Effect:** Instead of using `translateY`, which moves the button up, we will use `translate` along the X-axis with a value of `0.8` to achieve a subtle shift effect. This will improve the button's visual appeal during hover.

3. **Focus State Animation:** A new `focus` state transformation is added to the button to maintain consistency with the hover effect.
