### ISSUE TITLE
Refactor CSS and Apply Best Practices in client.css ✨

### ISSUE THREAD

**Issue by Nishitbaria** [OSCode-Community/OSCodeCommunitySite#1318]
Description:

The client.css file contains CSS code that could benefit from refactoring and adhering to best practices to improve maintainability, readability, and performance. This issue aims to refactor the existing CSS code in the client.css file while following industry best practices.

## Proposed Changes

1. **Use Meaningful Class Names:** Replace existing class names with descriptive and semantic names that clearly indicate the purpose of each element.

2. **Group Related Styles:** Group styles for the same element or related elements together to avoid duplication and improve code organization.

3. **Remove Unnecessary Specificity:** Avoid using overly specific selectors to prevent potential specificity conflicts and make the CSS easier to override.

4. **Avoid Excessive Use of ! important:** Reduce the use of the ! important declaration, as it can lead to specificity issues and hinder future maintainability.

5. **Optimize CSS Selectors:** Optimize CSS selectors for better performance and faster rendering.

6. **Consolidate Media Queries:** Where possible, consolidate media queries to minimize redundant code.

7. **Ensure Responsiveness:** Confirm that the CSS rules appropriately adjust for different screen sizes, especially for mobile and tablet devices.

Sure, here's the original "client.css" code and the refactored version side by side:

**Original "client.css" (Before):**

```css
/*--------------------------------------------------------------
# Clients
--------------------------------------------------------------*/
.clients .swiper-pagination {
  margin-top: 40px;
  position: relative;
}
.clients .swiper-pagination .swiper-pagination-bullet {
  width: 12px;
  height: 12px;
  background-color: var(--background-white);
  opacity: 1;
  border: 1px solid var(--backtotop-btn-color);
}
.clients-slider {
  padding-top: 50px;
}
.clients .swiper-pagination .swiper-pagination-bullet-active {
  background-color: var(--backtotop-btn-color);
}

@media only screen and (min-width: 600px) {
  .clients .swiper-slide {
    width: 100px !important;
    margin-right: 112px !important;
  }
}

.clients .swiper-slide {
  opacity: 0.5;
  filter: grayscale(100);
  cursor: pointer;
}
.clients .swiper-slide img {
  transition: 0.5s;
}
.clients .swiper-slide:hover {
  opacity: 1;
  filter: none;
}
.clients .swiper-slide:hover > img {
  transform: scale(1.2) rotateY(360deg);
}
.clients h1 {
  color: var(--backtotop-btn-color);
  text-shadow: 0 0 1px black;
  font-family: "Montserrat", sans-serif;
  font-size: 40px;
  font-weight: bold;
}
.enlarge {
  height: 60px;
  width: 200px;
  object-fit: contain;
}
@media only screen and (max-width: 600px) {
  .clients h1 {
    font-size: 27px;
  }
}
```

**Refactored "client.css" (After):**

```css
/*--------------------------------------------------------------
# Clients
--------------------------------------------------------------*/

/* Clients container styles */
.clients {
  /* Add styles here */
}

/* Pagination container styles */
.clients-pagination {
  margin-top: 40px;
  position: relative;
}

/* Pagination bullet styles */
.clients-pagination .pagination-bullet {
  width: 12px;
  height: 12px;
  background-color: var(--background-white);
  opacity: 1;
  border: 1px solid var(--backtotop-btn-color);
}

/* Active pagination bullet styles */
.clients-pagination .pagination-bullet-active {
  background-color: var(--backtotop-btn-color);
}

/* Slider styles */
.clients-slider {
  padding-top: 50px;
}

/* Slide styles */
.clients-slide {
  opacity: 0.5;
  filter: grayscale(100);
  cursor: pointer;
}

/* Image styles */
.clients-slide img {
  transition: 0.5s;
}

/* Hovered slide styles */
.clients-slide:hover {
  opacity: 1;
  filter: none;
}

/* Hovered image styles */
.clients-slide:hover > img {
  transform: scale(1.2) rotateY(360deg);
}

/* Heading styles */
.clients h1 {
  color: var(--backtotop-btn-color);
  text-shadow: 0 0 1px black;
  font-family: "Montserrat", sans-serif;
  font-size: 40px;
  font-weight: bold;
}

/* Enlarge image styles */
.enlarge {
  height: 60px;
  width: 200px;
  object-fit: contain;
}

/* Responsive styles for small screens */
@media only screen and (max-width: 600px) {
  /* Responsive heading styles */
  .clients h1 {
    font-size: 27px;
  }

  /* Responsive slide styles */
  .clients-slide {
    width: 100px;
    margin-right: 112px;
  }
}
```

Please note that the refactored version groups related styles, uses more meaningful class names, and organizes the CSS code to follow best practices. The changes aim to improve the maintainability and readability of the stylesheet.
