### ISSUE TITLE
Refactor gallery.css for Improved Code Structure and Readability ✨

### ISSUE THREAD

**Issue by Nishitbaria** [OSCode-Community/OSCodeCommunitySite#1333]
Description:
The current CSS code for the gallery section needs some improvements to enhance code structure and readability. I've refactored the gallery.css file to achieve better organization and maintainability while preserving the original functionality.

Refactored Changes:
1. Removed the commented out `text-shadow` property from the `.number` class to eliminate unnecessary clutter.

Before:
```css
.number {
  color: #5942e9;
  /* text-shadow: 2px 2px 3px rgb(166, 0, 255); */
  font-size: 40px;
  margin-top: 40px;
  letter-spacing: 1.5px;
  font-family: "Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif;
}
```

After:
```css
.number {
  color: #5942e9;
  font-size: 40px;
  margin-top: 40px;
  letter-spacing: 1.5px;
  font-family: "Franklin Gothic Medium", "Arial Narrow", Arial, sans-serif;
}
```

2. Combined multiple `box-shadow` properties in the `.image-slideshow` class into a single rule separated by commas for better readability.

Before:
```css
.image-slideshow {
  max-width: 700px;
  transition: 3s ease-in;
  margin: auto;
  position: relative;
  box-shadow: rgba(0, 0, 0, 0.56) 0px 22px 70px 4px,
              rgba(17, 17, 26, 0.1) 0px 4px 16px,
              rgba(17, 17, 26, 0.1) 0px 8px 24px,
              rgba(17, 17, 26, 0.1) 0px 16px 56px;
  cursor: pointer;
  margin-top: 40px;
}
```

After:
```css
.image-slideshow {
  max-width: 700px;
  transition: 3s ease-in;
  margin: auto;
  position: relative;
  box-shadow: rgba(0, 0, 0, 0.56) 0px 22px 70px 4px,
              rgba(17, 17, 26, 0.1) 0px 4px 16px,
              rgba(17, 17, 26, 0.1) 0px 8px 24px,
              rgba(17, 17, 26, 0.1) 0px 16px 56px;
  cursor: pointer;
  margin-top: 40px;
}
```

3. Moved the `transition: 3s ease-in;` property from `.image-slideshow img:hover` to `.image-slideshow img` to apply the transition to both hover and normal states of the image, simplifying the code.

Before:
```css
.image-slideshow img {
  width: 100%;
  box-shadow: rgba(0, 0, 0, 0.17) 0px -23px 25px 0px inset,
              rgba(0, 0, 0, 0.15) 0px -36px 30px 0px inset,
              rgba(0, 0, 0, 0.1) 0px -79px 40px 0px inset, 
              rgba(0, 0, 0, 0.06) 0px 2px 1px,
              rgba(0, 0, 0, 0.09) 0px 4px 2px, 
              rgba(0, 0, 0, 0.09) 0px 8px 4px,
              rgba(0, 0, 0, 0.09) 0px 16px 8px, 
              rgba(0, 0, 0, 0.09) 0px 32px 16px;
  object-fit: cover;
  transition: 3s ease-in;
}
```

After:
```css
.image-slideshow img {
  width: 100%;
  box-shadow: rgba(0, 0, 0, 0.17) 0px -23px 25px 0px inset,
              rgba(0, 0, 0, 0.15) 0px -36px 30px 0px inset,
              rgba(0, 0, 0, 0.1) 0px -79px 40px 0px inset, 
              rgba(0, 0, 0, 0.06) 0px 2px 1px,
              rgba(0, 0, 0, 0.09) 0px 4px 2px, 
              rgba(0, 0, 0, 0.09) 0px 8px 4px,
              rgba(0, 0, 0, 0.09) 0px 16px 8px, 
              rgba(0, 0, 0, 0.09) 0px 32px 16px;
  object-fit: cover;
  transition: 3s ease-in;
}
```

4. Removed the duplicate `box-shadow` property from the `.image-slideshow:hover` class, as it's the same as the one defined for `.image-slideshow`.

Before:
```css
.image-slideshow:hover {
  box-shadow: rgba(0, 0, 0, 0.56) 0px 22px 70px 4px;
  position: relative;
}
```

After:
```css
.image-slideshow:hover {
  position: relative;
}
```

With these changes, the CSS code for the gallery section is now more organized and maintainable while preserving the original styling and functionality. The refactored code ensures better readability and makes future modifications and updates easier.
