### ISSUE TITLE
fix:  CSS code for glowing text animation ✨

### ISSUE THREAD

**Issue by Nishitbaria** [OSCode-Community/OSCodeCommunitySite#1467]
Description:
I propose a refactor of the existing CSS code used for creating a glowing text animation. The current implementation is functional but can be optimized for better readability and maintainability. Below are the suggested changes:

Original CSS Code:
```css
<style>
    @keyframes glowing {
        0% {
            color: #ff84c1;
        }
        50% {
            color: #cf6af9;
        }
        100% {
            color: #ff84c1;
        }
    }

    .glowing-text {
        animation: glowing 2s linear infinite;
    }
</style>
```

Refactored CSS Code:
```css
<style>
    /* Define keyframes for glowing effect */
    @keyframes glowing {
        0%, 100% {
            color: #ff84c1;
        }
        50% {
            color: #cf6af9;
        }
    }

    /* Apply glowing effect to elements with class "glowing-text" */
    .glowing-text {
        animation: glowing 2s linear infinite;
    }
</style>
```

Changes Made:
1. In the `@keyframes glowing` rule, the keyframes at 0% and 100% now share the same style for `color`, as they both set it to `#ff84c1`. This reduces redundancy and improves maintainability.

Rationale for Refactor:
By making these changes, we enhance the code's clarity and make it easier to modify the glowing animation in the future. The refactored version retains the same functionality as the original code, but it is now more concise and easier to understand.

Please review the proposed changes and let me know your thoughts. If approved, I will proceed with updating the CSS code accordingly. Thank you!
